### ISSUE TITLE
In Visual3D how can you know which foot is in front

### ISSUE THREAD

**Issue by frajewatson** [cmasuki/open-code#24]
Hello :) 

Using V3D, I'd like to evaluate an expression that is different depending on which foot is in front of the other - does anyone have any experience doing this? Here is what I'd like to happen:

KINETIC_KINEMATIC::LFT::DistEndPos::y >= KINETIC_KINEMATIC::RFT::DistEndPos::y
If true - 
/Evaluate_Expression: DERIVED::PROCESSED::XCoM::y-KINETIC_KINEMATIC::LFT::DistEndPos::y
If false - 
/Evaluate_Expression: DERIVED::PROCESSED::XCoM::y-KINETIC_KINEMATIC::RFT::DistEndPos::y

Does anyone have experience of doing something similar or ideas of how to do it?

I appreciate any help/advice/ideas - thanks,
Fraje

**Comment by frajewatson** [comment]
I've solved this in MATLAB, but still unable to do it in Visual3D

`T = readtable('filename.csv');
frame = T{:,1};
LDSM = T{:,4};
RDSM = T{:,5};
LBOS = T{:,2};
RBOS = T{:,3};
res = RDSM;
res(LBOS > RBOS) = LDSM(LBOS > RBOS);
T2 = table(frame,res);

If anyone has any clues for Visual3D I'm still all ears as it'll make data syncing a lot easier :)

**Comment by dblana** [comment]
Do any of our Visual3D users have any ideas on how to help Fraje? Perhaps @Martin-Derby or @clevelandbarnett? Thank you! :pray:

**Comment by frajewatson** [comment]
I'm in touch with @clevelandbarnett and we're going to arrange a Skype session so that we can discuss how he does it :) Thanks for following up!
